# See https://docs.redoc.ly/cli/configuration/ for more information.
apiDefinitions:
  v1: "openapi/v1.yaml"
  v2: "openapi/v2.yaml"
lint:
  rules:
    no-unused-schemas: warning
referenceDocs:
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"