# See https://docs.redoc.ly/cli/configuration/ for more information.
apiDefinitions:
  main: "openapi/openapi.yaml"
extends:
  - recommended
lint:
referenceDocs:
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"